language: node_js

os: linux
dist: jammy

node_js:
  - "16.14.2"
  - node

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - if [[ `npm -v` != 6* ]]; then npm install -g npm@6; fi
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - docker pull docker.io/library/node:16.14.2-alpine3.15
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

install:
  - yarn install --frozen-lockfile

addons:
  artifacts:
    region: us-west-2
    paths:
      - $(git ls-files -o deploy/*/*-*.tar.gz | tr "\n" ":")
    target_paths:
      - /
  chrome: stable

services:
  - docker

script:
  - npm test
  - ./artifact.sh

jobs:
  allow_failures:
    - node_js: node
